version: '3.8'

services:
  db1:
    image: mongo:3.7
    container_name: User_DB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  db2:
    image: postgres:13
    container_name: Books_DB
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5454:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  cache:
    image: redis:latest
    container_name: redis_caching
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - backend
  
volumes:
  mongo-data:
  postgres-data:
  redis-data:

networks:
  backend:
    driver: bridge


